### ISSUE TITLE
Google keys

### ISSUE THREAD

**Issue by johnatasjmo** [crgeary/google-sheets-hugo-bookmarks#1]
Need some helps to configure the keys:

Netlify has the following keys:
```
GOOGLE_SHEETS_ID
GOOGLE_SHEETS_KEY
GOOGLE_SHEETS_EMAIL
```
Where ID is from the sheet. Key comes from google API Key.
The sheet is public.
What am I missing something?

**Comment by crgeary** [comment]
The sheet ID can be found from the URL.

Url: [docs.google.com/spreadsheets/d/1Bz5t-ShfgPCWzUJOoXjrXDwihpVp2SZuSsv80MW0qIw](https://docs.google.com/spreadsheets/d/1Bz5t-ShfgPCWzUJOoXjrXDwihpVp2SZuSsv80MW0qIw)
ID is: `1Bz5t-ShfgPCWzUJOoXjrXDwihpVp2SZuSsv80MW0qIw`
